### ISSUE TITLE
New script name poll - please vote!

### ISSUE THREAD

**Issue by JelmerT** [JelmerT/cc2538-bsl#103]
See #41 and #89 
Time for a (non-binding) poll:

[![](https://api.gh-polls.com/poll/01ER1M8B64HMA6XEX2XDEMGQZS/Ti-BSL)](https://api.gh-polls.com/poll/01ER1M8B64HMA6XEX2XDEMGQZS/Ti-BSL/vote)
[![](https://api.gh-polls.com/poll/01ER1M8B64HMA6XEX2XDEMGQZS/simple-bsl)](https://api.gh-polls.com/poll/01ER1M8B64HMA6XEX2XDEMGQZS/simple-bsl/vote)
[![](https://api.gh-polls.com/poll/01ER1M8B64HMA6XEX2XDEMGQZS/cc-bsl%20)](https://api.gh-polls.com/poll/01ER1M8B64HMA6XEX2XDEMGQZS/cc-bsl%20/vote)
[![](https://api.gh-polls.com/poll/01ER1M8B64HMA6XEX2XDEMGQZS/cc2538-bsl)](https://api.gh-polls.com/poll/01ER1M8B64HMA6XEX2XDEMGQZS/cc2538-bsl/vote)
[![](https://api.gh-polls.com/poll/01ER1M8B64HMA6XEX2XDEMGQZS/cc-Loader)](https://api.gh-polls.com/poll/01ER1M8B64HMA6XEX2XDEMGQZS/cc-Loader/vote)
[![](https://api.gh-polls.com/poll/01ER1M8B64HMA6XEX2XDEMGQZS/Other%20(comment))](https://api.gh-polls.com/poll/01ER1M8B64HMA6XEX2XDEMGQZS/Other%20(comment)/vote)

**Comment by JelmerT** [comment]
I like `simple-bsl` since the idea of the script is that it can support multiple BSLs in the future, not just Ti or CC ones. 
The code should also be pretty modular to be able to be expanded in this way.

**Comment by omerk** [comment]
While having a name that will allow future expandability makes sense, realistically what are the chances of other devices being added? If the answer is "likely", then `simple-bsl` would do a good job as a generic name. If it is more of a "would be nice if it were to happen", my vote is on `cc-bsl` as it is what the script is, in its current state.

**Comment by JelmerT** [comment]
The results are pretty clear! `cc-bsl` it is!

I will rename the repo and script and bump the version.

I'll try to warn and fix any tools/repos that use the script.
