### ISSUE TITLE
Sonoff zigbee 3.0 USB dongle plus doesn't stay connected as a ROUTER - goes offline

### ISSUE THREAD

**Issue by jcat59** [JelmerT/cc2538-bsl#134]
I flashed my dongle successfully with the below command and had it working as a router. The problem is that after awhile the router will go offline and no longer be responsive. From my research - the way to fix this is to configure the device to report periodically to the coordinator (around 4 minutes).  I’m not sure if this is related or true or not. The router has never stayed online enough for any device to connect to it (other than coordinator).

Is there some way I can update the device to report to the coordinator so it doesn't go offline? If I have to reflash, can you guide me how I can alter the command line below?

python cc2538-bsl.py -p COM3 -evw --ieee-address 00:12:4b:00:01:4d:12:34 --bootloader-sonoff-usb CC1352P2_CC2652P_launchpad_router_20221102.hex

I'm using ZHA in home assistant just in case that makes any difference.

**Comment by JelmerT** [comment]
@jcat59 This repo is just for the script that uploads your binary to your dongle. Looks like your issue is related to the binary you're uploading, so you'll have to re-open this in that repo.

Closing this one.
