### ISSUE TITLE
Timeout waiting for ACK/NACK

### ISSUE THREAD

**Issue by FreeKillerLP** [JelmerT/cc2538-bsl#135]
I tried to update my "USB Zigbee 3.0 USB Dongle Plus,EFR32MG21 + CH9102F Zigbee USB-Stick". I always get this error message (1):

```
sonoff
Opening port COM3, baud 500000
Reading data from C:\Users\Miche\Desktop\cc2538-bsl-master\CC1352P2_CC2652P_launchpad_coordinator_20221226.hex
Your firmware looks like an Intel Hex file
Connecting to target...
ERROR: Timeout waiting for ACK/NACK after 'Synch (0x55 0x55)'
```

I pressed the boot button while putting the stick into my usb port to enable the boot-mode, I even tried to use the this Py-script in order to get to the boot-mode: https://github.com/Nerdiyde/Sonoff_zigbee_3.0_USB_dongle_plus_bootloader_script

the tools i have tried: 
- SmartRF Flash Programmer 2
- Zigstar
- cc2538-bsl.py

but I just get the massage above (1)

my command for cc2535-bsl.py:

`    python C:\Users\Miche\Downloads\cc2538-bsl-master\cc2538-bsl.py -p COM3 -e -v -w --bootloader-sonoff-usb C:\Users\Miche\Desktop\cc2538-bsl-master\CC1352P2_CC2652P_launchpad_coordinator_20221226.hex
`

**Comment by tube0013** [comment]
You have an EFR32MG21

You are trying to flash cc2652 fw.
