### ISSUE TITLE
Move size check before erase

### ISSUE THREAD

**Issue by git-developer** [JelmerT/cc2538-bsl#140]
@galmok reported in [git-developer/ti-cc-tool#6](https://github.com/git-developer/ti-cc-tool/issues/6) that the data size is checked after flash memory is erased. Moving this check before the erase command could improve the user experience.

**Comment by galmok** [comment]
#139 I already submitted such an improvement request. :⁠-⁠)

**Comment by git-developer** [comment]
OK then, one should be enough :)
