### ISSUE TITLE
ERROR: int() can't convert non-string with explicit base

### ISSUE THREAD

**Issue by ccle610** [JelmerT/cc2538-bsl#171]
Because I have exactly this Problem too, I will re-open it:
I have a problem while flashing my CC2652P. It says it's done verifying with a match but then goes on with an int error.

python cc2538-bsl.py -p COM4 -e -v -w --bootloader-sonoff-usb CC1352P2_CC2652P_launchpad_coordinator_20211217.hex

sonoff
Opening port COM4, baud 500000
Reading data from CC1352P2_CC2652P_launchpad_coordinator_20211217.hex
Your firmware looks like an Intel Hex file
Connecting to target...
CC1350 PG2.0 (7x7mm): 352KB Flash, 20KB SRAM, CCFG.BL_CONFIG at 0x00057FD8
Primary IEEE Address: 00:12:4B:00:24:C2:A2:6E
    Performing mass erase
Erasing all main bank flash sectors
    Erase done
Writing 360448 bytes starting at address 0x00000000
Write 104 bytes at 0x00057F980
    Write done
Verifying by comparing CRC32 calculations.
    Verified (match: 0xba5c19c5)
ERROR: int() can't convert non-string with explicit base

When trying to start zigbee2mqtt it fails:

Zigbee2MQTT:info 2024-03-27 17:31:55: Starting Zigbee2MQTT version 1.36.0 (commit #unknown)
Zigbee2MQTT:info 2024-03-27 17:31:55: Starting zigbee-herdsman (0.35.1)
Zigbee2MQTT:error 2024-03-27 17:32:06: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2024-03-27 17:32:06: Failed to start zigbee
Zigbee2MQTT:error 2024-03-27 17:32:06: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2024-03-27 17:32:06: Exiting...
Zigbee2MQTT:error 2024-03-27 17:32:06: undefined

Any Idea on how to fix this?

Thanks!

**Comment by tonyaajjackson** [comment]
Fixed in #168, but hasn't been merged yet. You can fix this in the Python file yourself by changing the line shown here:
https://github.com/JelmerT/cc2538-bsl/pull/168/commits/24c9010a570a324a64e79452af4b17b9a5a3d88e
