### ISSUE TITLE
Default baud rate 500k for cc2538 OK?

### ISSUE THREAD

**Issue by uknoblic** [JelmerT/cc2538-bsl#43]
Hi,

is seems that the default baud rate used for your script is 500000. Did you test this speed with the cc2538? http://www.ti.com/lit/an/swra466a/swra466a.pdf states that the cc2538 only supports 460800.

Regards

Ulf

**Comment by JelmerT** [comment]
This speed (500000) does indeed work with the CC2538. Mainly tested by trial and error on the SmartRF06 boards. Never heard any complaints.

Are you seeing problems with a specific platform?

Note that this speed is only used in the beginning of the script, before enabling the external crystal.

**Comment by uknoblic** [comment]
Thanks, no problems with this baud rate. As we had the issue with the FTDI converter before using Georges's fix, i was wondering if the baud rate could be the problem. Solved!
