### ISSUE TITLE
Also read mem size when getting chip ID

### ISSUE THREAD

**Issue by JelmerT** [JelmerT/cc2538-bsl#5]
GetChipID only reads the chip id at the moment. (Which is 0xb964 apparently)

We could expand this to also read the info page, which would give us SRAM size, Flash size and both IEEE addresses. 

This would in turn give us the possibility to better check the boot loader backdoor enable bit.

**Comment by g-oikonomou** [comment]
I'm working on this one (for all supported chips) and hope to have something soon.

**Comment by JelmerT** [comment]
:+1: 

I started working on this at some point, see this [branch](https://github.com/JelmerT/cc2538-bsl/tree/feature/readsize), but never merged it back into master (only for cc2538)
