### ISSUE TITLE
cc2530/cc2531 support

### ISSUE THREAD

**Issue by itsmepetrov** [JelmerT/cc2538-bsl#73]
Any chance of adding support for cc2530/cc2531?

**Comment by g-oikonomou** [comment]
Have you checked cc-tool?

https://github.com/scott-42/cc-tool
https://github.com/dashesy/cc-tool

Not sure which one is newer

**Comment by itsmepetrov** [comment]
Yes, I've already checked, but I haven't seen any support for `.bin` images for `sbl` loader. As I understand it works only for full images (.hex) and only via `cc-debugger`.

**Comment by g-oikonomou** [comment]
I personally don't plan to work on adding support for that chip family, no.

cc-tool uses the debug interface last time I checked, yes. As far as I can tell, this sbl is not on chip ROM, is it? So one has to build it and then program the device with it, it sits in the low area of flash. If one can build it then one can certainly create a combined hex/bin that contains the bootloader + the main application.

If the protocol is similar to the one used by CC2538 then it should not be too big effort to support if you were to decide to try.

**Comment by JelmerT** [comment]
Closing this for now, support for CC2530/31 would be great, but it's not an easy add-on, and there's no one volunteering at this moment. 
This ties in to the previous idea of expanding the script into a universal tool for all chips with a serial bootloader flashing mechanism.

Pull requests are welcome though!
