### ISSUE TITLE
'module' object has no attribute 'serialposix' under git-bash on windows

### ISSUE THREAD

**Issue by librasungirl** [JelmerT/cc2538-bsl#74]
https://github.com/JelmerT/cc2538-bsl/blob/master/cc2538-bsl.py#L217, 
`if isinstance(self.sp, serial.serialposix.Serial):` may cause some platform issue, as on windows, it should be serialwin32, other than serialposix

**Comment by JelmerT** [comment]
I don't have a windows system to test this problem, can you submit a pull request to fix this?

**Comment by librasungirl** [comment]
@JelmerT , #75 is submitted to fix this. Validated it works under Window OS, and Ubuntu/Mac OS as well.
Please help to review it. Thanks.

**Comment by JelmerT** [comment]
closed by #75
