### ISSUE TITLE
No serial port found while trying to flash CC1310 LAUNCHPAD with contiki demo code.

### ISSUE THREAD

**Issue by Mix213** [JelmerT/cc2538-bsl#81]
Hi,
I am using CC1310 LAUNCHPADXL. I am trying to flash cc26xx-demo code of Contiki.

I have modified the bootloader settings in cc26xxware/startup_files/ccfg.c file in reference to the document http://www.ti.com/lit/ug/swcu117h/swcu117h.pdf on the page:725.
BOOTLOADER_ENABLE = 0xC5 (Bootloader enable. SET_CCFG_BL_CONFIG_BOOTLOADER_ENABLE in CC13xx/CC26xxware)
BL_LEVEL = 0x1 (Active low. SET_CCFG_BL_CONFIG_BL_LEVEL in CC13xx/CC26xxware)
BL_PIN_NUMBER = 0xFF (DIO 11. SET_CCFG_BL_CONFIG_BL_PIN_NUMBER in CC13xx/CC26xxware)
BL_ENABLE = 0xC5 (Enable "failure analysis". SET_CCFG_BL_CONFIG_BL_ENABLE in CC13xx/CC26xxware)

For the Command:- 
sudo make TARGET=srf06-cc26xx BOARD=launchpad/cc1310 cc26xx-demo.upload

Displayed ERROR: 
![contiki 1](https://user-images.githubusercontent.com/47058385/51788387-8ff38d80-21a3-11e9-8856-0bb69a7e4240.png)

While checking the Serial ports at /dev, the board gets resolved as ttyACM0 and ttyACM1. 

Can you help a way to upload the code on the launchpad?

**Comment by JelmerT** [comment]
With the -p option you can define the port the script connects on. So if you add `-p /dev/ttyACM1` when you call the script it should try that serial port.

**Comment by JelmerT** [comment]
But I'm suspecting something else is wrong here, since a serial port with that name should automatically be detected by the script.
Are you sure those ports are there and available? No other process is using them?

**Comment by Mix213** [comment]
So I tried adding /dev/ttyACM0, I get ERROR: Timeout waiting for ACK/NACK after 'Synch (0x55 0x55)'. 

I am sure the ports are there and not being used by any other process.

**Comment by Mix213** [comment]
Sir, can you please help me out. I am trying to flash my cc1310 launchpad with the following command, 
make TARGET=srf06-cc26xx BOARD=launchpad/cc1310 cc26xx-web-demo.upload /dev/ttyACM0

Getting ERROR: Timeout waiting for ACK/NACK after 'Synch (0x55 0x55)'.

![contiki](https://user-images.githubusercontent.com/47058385/51925970-2a5b0780-2416-11e9-9adf-fb77f8a429d3.png)

**Comment by JelmerT** [comment]
Make sure that the CC1310 chip on the launchpad has its bootloader enabled. Wipe it over JTAG, or flash the firmware with an enabled bootloader via JTAG before you try the serial bootloader.

**Comment by Mix213** [comment]
Sir, 
Can you elaborate it, please? How do I do that? 
I have made the necessary changes in the file cc13xxware/startup_files/ccfg.c.

**Comment by JelmerT** [comment]
Just wipe the chip itself over JTAG. The changes you're making are for the firmware you want to flash, not the firmware that is already on the actual chip.

**Comment by Mix213** [comment]
I am sorry but it's not clear to me. How do I do that? Hardware connections? What program should i use? What commands? Is there a reference for it?

**Comment by JelmerT** [comment]
Use TI CCS to wipe the chip, read the documentation on your hardware, here is a good place to start: http://dev.ti.com/tirex/#/?link=Software%2FSimpleLink%20CC13x0%20SDK%2FSimpleLink%20Academy

**Comment by JelmerT** [comment]
Closing this since the problem doesn't seem to be related to this project
