### ISSUE TITLE
CC1350 sensortag : write error "Send data (0x24)"

### ISSUE THREAD

**Issue by toothless90x** [JelmerT/cc2538-bsl#83]
The device is hardwired for DIO 2 & 3 for Bootloader UART comm. 
While trying to flash the board using the script, the following error turns. 
terminal log also attached for the reference. 
How to solve this ? 

[screen1.log](https://github.com/JelmerT/cc2538-bsl/files/2851260/screen1.log)

**Comment by JelmerT** [comment]
Can't see the log you linked

**Comment by toothless90x** [comment]
Its the same file. I made sure it opens in any notepad. 
[screen1.log](https://github.com/JelmerT/cc2538-bsl/files/2851815/screen1.log)

**Comment by JelmerT** [comment]
My bad, addblocker was a little too blocky

**Comment by JelmerT** [comment]
Does the error always come at the same time? It looks like communication is working, but then randomly fails.
Did you remove R21 and R22 on the board? And you properly connected ground?

**Comment by toothless90x** [comment]
yes. always at happens.
Those R21 and R22 are removed for DIO2,3 connection. 
Ground is connected properly.

**Comment by JelmerT** [comment]
Just want to make sure the digital mic isn't interfering with the UART.

Not sure about this one. Have you tried a different source file? Maybe smaller to see what difference that that makes. And you could try slowing down the baudrate.

**Comment by toothless90x** [comment]
For different source file, when I try to make .bin for hello-world with following cmd in git clone
`make TARGET=srf06-cc26xx BOARD=sensortag/cc1350 hello-world.bin`
the .bin file size is 131.1kb. The interesting factor is, for any test example when .bin is made, the file size is again 131.1 kb. 
I dont know why it happens like this .

**Comment by JelmerT** [comment]
I don't have contiki-ng setup right now, so I can't check. But can you try a different project that isn't hello-world?

**Comment by g-oikonomou** [comment]
I would be very surprised to see a .bin file with a size other than exactly 128KB :)

**Comment by g-oikonomou** [comment]
To the topic in hand, are you sure you are not simply falling victim to dodgy wires? What are you physical connections like? What do you have connected to what?

**Comment by toothless90x** [comment]
Got it resolved. It was an voltage fluctuation from MOSFET (Used to power reset the Board-CC1350), which interrupts the Send data inbetween the process. 

Connection: Host PC - FTDI - hardwired sensortag CC1350(mounted on custom made Mother board).


@JelmerT  Its turns out to be same size .bin (131.1Kb) for cc26xx-web-demo example also. :(
@g-oikonomou Regarding the .bin file issue, shall I open a new thread ?

**Comment by g-oikonomou** [comment]
The bin file size is not an issue, it's perfectly expected. Just don't try to estimate firmware code footprint by looking at the file size of the .bin. Use `arm-none-eabi-size` on the .elf. No need to open a separate thread.

**Comment by JelmerT** [comment]
Great, looks like the problem was found, closing this.

Thanks for the help @g-oikonomou
